package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"
)

// Token is a minted access credential bound to exactly one route.
type Token struct {
	ID         int64
	JTI        string
	Label      string
	Route      string
	Msg        string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
	LastUsedAt *time.Time
}

// Active reports whether the token is currently usable at the given instant.
func (t *Token) Active(at time.Time) bool {
	if t.RevokedAt != nil {
		return false
	}
	if t.ExpiresAt != nil && !t.ExpiresAt.After(at) {
		return false
	}
	return true
}

// CreateTokenInput is the payload for minting a new token.
type CreateTokenInput struct {
	JTI       string     // caller-provided (generated by token package); must be unique
	Label     string     // human-readable identifier; unique among active tokens
	Route     string     // named route this token grants access to
	Msg       string     // optional welcome message (carried in JWT)
	ExpiresAt *time.Time // nil = never expires
}

func (s *Store) CreateToken(ctx context.Context, in CreateTokenInput) (*Token, error) {
	if in.JTI == "" || in.Label == "" || in.Route == "" {
		return nil, errors.New("CreateToken: jti, label, and route are required")
	}
	created := s.now()
	res, err := s.db.ExecContext(ctx, `
		INSERT INTO tokens (jti, label, route, msg, created_at, expires_at)
		VALUES (?, ?, ?, ?, ?, ?)`,
		in.JTI, in.Label, in.Route, in.Msg,
		timeArg(created), nullableTimeArg(in.ExpiresAt),
	)
	if err != nil {
		if isUniqueViolation(err) {
			return nil, fmt.Errorf("%w: label %q is already in use", ErrConflict, in.Label)
		}
		return nil, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return nil, err
	}
	return &Token{
		ID:        id,
		JTI:       in.JTI,
		Label:     in.Label,
		Route:     in.Route,
		Msg:       in.Msg,
		CreatedAt: created,
		ExpiresAt: in.ExpiresAt,
	}, nil
}

const tokenCols = `id, jti, label, route, msg, created_at, expires_at, revoked_at, last_used_at`

func scanToken(row interface {
	Scan(...any) error
}) (*Token, error) {
	var (
		t          Token
		createdStr string
		expires    sql.NullString
		revoked    sql.NullString
		lastUsed   sql.NullString
	)
	if err := row.Scan(&t.ID, &t.JTI, &t.Label, &t.Route, &t.Msg,
		&createdStr, &expires, &revoked, &lastUsed); err != nil {
		return nil, err
	}
	created, err := time.Parse(time.RFC3339Nano, createdStr)
	if err != nil {
		return nil, fmt.Errorf("parse created_at %q: %w", createdStr, err)
	}
	t.CreatedAt = created.UTC()
	if t.ExpiresAt, err = nullableTime(expires); err != nil {
		return nil, err
	}
	if t.RevokedAt, err = nullableTime(revoked); err != nil {
		return nil, err
	}
	if t.LastUsedAt, err = nullableTime(lastUsed); err != nil {
		return nil, err
	}
	return &t, nil
}

func (s *Store) GetTokenByJTI(ctx context.Context, jti string) (*Token, error) {
	row := s.db.QueryRowContext(ctx,
		`SELECT `+tokenCols+` FROM tokens WHERE jti = ?`, jti)
	t, err := scanToken(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	return t, err
}

// GetActiveTokenByLabel returns the (at most one) non-revoked token for a label.
func (s *Store) GetActiveTokenByLabel(ctx context.Context, label string) (*Token, error) {
	row := s.db.QueryRowContext(ctx,
		`SELECT `+tokenCols+` FROM tokens WHERE label = ? AND revoked_at IS NULL`, label)
	t, err := scanToken(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	return t, err
}

func (s *Store) ListTokens(ctx context.Context) ([]Token, error) {
	rows, err := s.db.QueryContext(ctx,
		`SELECT `+tokenCols+` FROM tokens ORDER BY created_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Token
	for rows.Next() {
		t, err := scanToken(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *t)
	}
	return out, rows.Err()
}

// RevokeToken marks a token revoked. Returns ErrNotFound if no such jti exists,
// or silently succeeds if the token was already revoked.
func (s *Store) RevokeToken(ctx context.Context, jti string) error {
	now := s.now()
	res, err := s.db.ExecContext(ctx,
		`UPDATE tokens SET revoked_at = ? WHERE jti = ? AND revoked_at IS NULL`,
		timeArg(now), jti)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n > 0 {
		// Also invalidate any live sessions bound to this token.
		if _, err := s.db.ExecContext(ctx,
			`DELETE FROM sessions WHERE token_id = (SELECT id FROM tokens WHERE jti = ?)`,
			jti); err != nil {
			return err
		}
		return nil
	}
	// No row updated — either absent or already revoked. Distinguish.
	var exists int
	if err := s.db.QueryRowContext(ctx,
		`SELECT 1 FROM tokens WHERE jti = ?`, jti).Scan(&exists); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrNotFound
		}
		return err
	}
	return nil
}

// UnrevokeToken clears revoked_at. Fails with ErrConflict if another active token
// holds the same label (since tokens_label_active is a partial unique index).
func (s *Store) UnrevokeToken(ctx context.Context, jti string) error {
	_, err := s.db.ExecContext(ctx,
		`UPDATE tokens SET revoked_at = NULL WHERE jti = ?`, jti)
	if err != nil {
		if isUniqueViolation(err) {
			return fmt.Errorf("%w: another active token holds this label", ErrConflict)
		}
		return err
	}
	return nil
}

// TouchTokenLastUsed updates last_used_at. Best-effort — errors are returned but
// the caller may choose to log and continue.
func (s *Store) TouchTokenLastUsed(ctx context.Context, id int64) error {
	_, err := s.db.ExecContext(ctx,
		`UPDATE tokens SET last_used_at = ? WHERE id = ?`,
		timeArg(s.now()), id)
	return err
}

func isUniqueViolation(err error) bool {
	// modernc.org/sqlite returns a driver-specific error; the textual form
	// contains "UNIQUE constraint failed". Sufficient for our purposes and
	// avoids coupling to an internal error code type.
	return err != nil && strings.Contains(err.Error(), "UNIQUE constraint failed")
}
